disabled_rules:
  - nesting
  - trailing_newline
  - trailing_whitespace
  - todo
  - closure_parameter_position
  - unused_closure_parameter
  - mark
  - weak_delegate
  - identifier_name
  - empty_parameters

included:
  - Sources

excluded:
  - Configurations

line_length: 300
type_name:
  min_length: 3
  max_length:
    warning: 45
    error:  50
  excluded:
    - id
    - €

file_length:
  warning: 200
  error: 300
  ignore_comment_only_lines: true

identifier_name:
  min_length: 2
  max_length:
    warning: 35
    error:  45

type_body_length:
  - 100 # warning
  - 200 # error

function_parameter_count:
  - 4 # warning
  - 5 # error

function_body_length:
  - 15 # warning
  - 25 # error
