disabled_rules:
  - nesting
  - trailing_newline
  - trailing_whitespace
  - todo
  - closure_parameter_position
  - unused_closure_parameter
  - mark
  - weak_delegate
  - identifier_name
  - empty_parameters

included:
  - Source

excluded:
  - Carthage
  - Pods
  - Configurations

line_length: 300
type_name:
  min_length: 3
  max_length:
    warning: 40
    error:  45
excluded:
- id

file_length:
  - 200 # warning
  - 300 # error

variable_name:
  min_length: 2
  max_length:
    warning: 35
    error:  45

type_body_length:
  - 100 # warning
  - 200 # error

function_parameter_count:
  - 4 # warning
  - 5 # error

function_body_length:
  - 15 # warning
  - 25 # error
