default_platform(:ios)

$plist_path = "Source/Application/Zhip-Info.plist"

desc "Push a new beta build to TestFlight"
lane :beta do
  begin
    # Update provisioning profiles and certificates
    match(type: "appstore", readonly: true)
    
    # Build the IPA
    build_app(scheme: "Zhip")

    upload_to_testflight

    slack(
      message: "AppStore Connect (TestFlight) successfully parsed build",
      success: true
    )
  
    clean_build_artifacts

  rescue => exception
    on_error(exception)
  end
end

desc "Run unit tests for each opened pull request"
lane :test do
  run_tests(
    scheme: "ZhipTests",
    clean: false,
    slack_only_on_failure: true
  )
end

# Lane helpers
def on_error(exception)
  slack(
    message: "Lane failed with exception : #{exception}",
    success: false
  )
  raise exception
end